apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "updatemanager.onesi.de/v1alpha1",
          "kind": "ClusterUpdate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "updatecontroller",
              "app.kubernetes.io/instance": "clusterupdate-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "clusterupdate",
              "app.kubernetes.io/part-of": "updatecontroller"
            },
            "name": "clusterupdate-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "updatemanager.onesi.de/v1alpha1",
          "kind": "NodeUpdate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "updatecontroller",
              "app.kubernetes.io/instance": "nodeupdate-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "nodeupdate",
              "app.kubernetes.io/part-of": "updatecontroller"
            },
            "name": "nodeupdate-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-11-14T17:33:22Z"
    operators.operatorframework.io/builder: operator-sdk-v1.32.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: updatecontroller.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterUpdate is the Schema for the clusterupdates API
      displayName: Cluster Update
      kind: ClusterUpdate
      name: clusterupdates.updatemanager.onesi.de
      version: v1alpha1
    - description: NodeUpdate is the Schema for the nodeupdates API
      displayName: Node Update
      kind: NodeUpdate
      name: nodeupdates.updatemanager.onesi.de
      version: v1alpha1
  description: Manage Cluster and Node Updates
  displayName: UpdateController
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - clusterupdates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - clusterupdates/finalizers
          verbs:
          - update
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - clusterupdates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - nodeupdates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - nodeupdates/finalizers
          verbs:
          - update
        - apiGroups:
          - updatemanager.onesi.de
          resources:
          - nodeupdates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: updatecontroller-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: updatecontroller
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: updatecontroller
          control-plane: controller-manager
        name: updatecontroller-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: updatecontroller-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: updatecontroller-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - update
  links:
  - name: Updatecontroller
    url: https://updatecontroller.domain
  maintainers:
  - email: dustinh@onesi.de
    name: dusthoff
  maturity: alpha
  provider:
    name: Dustin Hoffmann
    url: https://github.com/DustHoff
  version: 0.0.1
