# permissions for end users to edit nodeupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodeupdate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: updatecontroller
    app.kubernetes.io/part-of: updatecontroller
    app.kubernetes.io/managed-by: kustomize
  name: nodeupdate-editor-role
rules:
- apiGroups:
  - updatemanager.onesi.de
  resources:
  - nodeupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - updatemanager.onesi.de
  resources:
  - nodeupdates/status
  verbs:
  - get
