apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dusthoff
  namespace: olm
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  image: ghcr.io/dusthoff/operator-catalog:latest
  displayName: Update Operator
  publisher: DustHoff Github
  updateStrategy:
    registryPoll:
      interval: 60m