apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: update-operator
  namespace: operators
spec:
  channel: stable
  name: updatecontroller
  source: dusthoff
  sourceNamespace: olm