name: Release
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: generate catalog channel config
        run: for tag in $(git ls-remote --tags origin | tr "\t" " " | cut -d " " -f2 | tr -d "refs\/tags\/"); do echo "  - name: updatecontroller.v$tag" >> catalog/operator.yaml; done
      - name: generate catalog bundle config
        run: for tag in $(git ls-remote --tags origin | tr "\t" " " | cut -d " " -f2 | tr -d "refs\/tags\/"); do ./bin/opm render ghcr.io/dusthoff/update-operator-bundle:$tag -o yaml >> catalog/operator.yaml; done
      - name: validate catalog config
        run: ./bin/opm validate catalog
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: generate Bundle Files
        run: make bundle IMG=ghcr.io/dusthoff/update-operator:${GITHUB_REF##*/} VERSION=${GITHUB_REF##*/}
      - name: Docker meta
        id: meta-operator
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/update-operator
      - name: Build and push operator
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta-operator.outputs.tags }}
          labels: ${{ steps.meta-operator.outputs.labels }}
      - name: Docker meta
        id: meta-bundle
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/update-operator-bundle
      - name: Build and push operator-bundle
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: bundle.Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta-bundle.outputs.tags }}
          labels: ${{ steps.meta-bundle.outputs.labels }}
      - name: Build and push operator-catalog
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: catalog.Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64

          tags: ghcr.io/dusthoff/operator-catalog:latest
          labels: ${{ steps.meta-bundle.outputs.labels }}
