name: Release
on:
  push:
    branch: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta-operator
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/update-operator
      - name: Build and push operator
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta-operator.outputs.tags }}
          labels: ${{ steps.meta-operator.outputs.labels }}
      - name: Docker meta
        id: meta-bundle
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/update-operator-bundle
      - name: Build and push operator-bundle
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: bundle.Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta-bundle.outputs.tags }}
          labels: ${{ steps.meta-bundle.outputs.labels }}
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: build catalog
        run: make catalog-build catalog-push VERSION=${GITHUB_REF##*/}
