name: Release
on:
  push:
    branch: "*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - run: go version
      - uses: shivanshs9/setup-k8s-operator-sdk@v1
        with:
          version: "^1.32.0"
      - name: bundle operator
        run: make bundle
      - name: build-bundle operator
        run: make bundle catalog-build catalog-push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/updatecontroller/operator
      - name: Build and push operator
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dusthoff/updatecontroller/operator-bundle
      - name: Build and push operator
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: bundle.Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}